### ISSUE TITLE
oci_pull from private gitlab container registry

### ISSUE THREAD

**Issue by oakad** [bazel-contrib/rules_oci#422]
Bazel 6.4.0/rules_oci-1.4.2

I need to pull some base images from a privately hosted gitlab registry; I do the usual "docker login"/"crane auth login" and everything works just fine.

However, I cannot use the same registry with `oci_pull`, it always fails. From the look of it, the scenario is not even supported: gitlab requires a temporary token acquisition and while big, public gitlab has an entry in `_WWW_AUTH` array, my private gitlab instance obviously has none.

So, what is the expected approach for this sort of operation?

In general, I wonder why `oci_pull` is implemented in terms of custom and incorrect http download flow which is guaranteed to keep breaking instead of using `crane pull` or some other more reliable method?

I would also like to point out that the days of public docker image registries are counted, with both Docker and Google pushing their users toward authenticated access. For rules_oci to be of any utility, authentication must be properly addressed, otherwise we will be stuck without the ability to build images with Bazel.

**Comment by alexeagle** [comment]
We support credential helpers, which I think is the way to get the temporary token. @thesayyn I don't see docs about credential helpers on the repo?

> why oci_pull is implemented in terms of custom and incorrect http download flow which is guaranteed to keep breaking instead of using crane pull 
The Bazel Downloader has a bunch of features, and our goal is to rely on it exclusively. The primary feature is correct, content-based caching in the `--repository_cache`, and also the ability for Bazel remote execution systems to perform a remote download so the pull never needs to happen on the machine where Bazel runs.

**Comment by thesayyn** [comment]
We are still in the phase of fixing bazel downloader to fit the needs of the rulesets. As Alex pointed out using bazel downloader is the right way to fetch remote content for various reasons.

 As for _WWW auth, the reason why it exists is clearly stated above the variable, and we can't keep expanding it forever. One solution is to allow users to provide WWW auth entry for their private registries. 
 
See: https://github.com/bazel-contrib/rules_oci/issues/126

**Comment by oakad** [comment]
Credential helpers don't help here; the credentials are fine, the problem is with the redirect/reauth flow. What will be of help is support for download helper of some sort which gets docker tag in and returns image tarball out.

You pull go-containerregistry as dependency anyway. The safe approach will be to use a helper which calls into it, not the horrible bazel http support which keeps breaking on mundane proxy use.

**Comment by thesayyn** [comment]
I don't understand your argument. credential helpers are another way to perform the auth outside of bazel and provide the necessary headers to allow access. WWW auth is the basic authentication mechanism we can't support fully due to bazel limitations. 

> You pull go-containerregistry as dependency anyway

It's not a matter of if we fetch it or not, it's about performance, storage efficiency and caching. running external programs to perform fetches are not good for following reasons,

- Not cacheable
- Not incremental, as in one attribute change causes everything to be downloaded again, even if the image has a single layer change.
- Not aware of bazel flags, --timeout_scaling --credential_helper and other HTTP related flags.
- Known to cause network congestion on heavy usage due to lack of a limiter
- Not efficient in terms of storage, since layers across different images are not deduped.
- Not gonna work with B-WO-B mode of bazel

Considering all these points, we are not likely to change the implementation of oci_pull. 

> not the horrible bazel http support

Best course of action for you is to file an issue to bazel so those shortcomings address these shortcomings. You can even contribute them yourself. It's open source for a reason

**Comment by thesayyn** [comment]
You always have the option of making your own version of oci_pull that uses crane to pull instead.

**Comment by thesayyn** [comment]
Closing this is favor of https://github.com/bazel-contrib/rules_oci/issues/126
