### ISSUE TITLE
oci_push --repository and --repotags flags should accept file paths 

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/rules_oci#46]
Useful for stamping, for example

**Comment by alexeagle** [comment]
already changed `repotags` to take a file argument

**Comment by thesayyn** [comment]
closing this as we already support stamped `repotags`

**Comment by seh** [comment]
Now that the repository name is back out of the "remote_tags" attribute and in its own "repository" attribute, we lost this ability that we had for a brief while.

The discussion here sounds like the maintainers were convinced of the value of stamping the repository name, but since then we've wavered on which information gets conveyed in which attribute values. Yes, if we could convey the repository name in the stamp-friendly "remote_tags" attribute, this need would be covered, but with the separate "repository" attribute we have today, I think there's still an open gap.

**Comment by seh** [comment]
See #338 for taking the repository from the content of a file.
