### ISSUE TITLE
Authentication fail on some private registry

### ISSUE THREAD

**Issue by pierfale** [bazel-contrib/rules_oci#544]
Hello,

I am in the process of migrating rules_docker to rules_oci.
I'm having a few problems when pulling some images from a private registry.
With rules_docker it worked.
But with rules_oci, I get 401 error.
 I need to use the credential_helper feature to succeed at pull, by exchanging tokens  by hand using a basic auth:

```
username="nologin"
password="..."

input=$(cat)
uri=$(jq -r ".uri" <<< $input)
authh=$(curl -v "$uri" 2>&1 /dev/null|grep "www-authenticate:")
authuri=$(echo $authh | sed 's/.*realm="\([^"]*\)".*/\1/')
authhost=$(echo $authuri | sed 's/^https:\/\/\(.*\)/\1/')
authservice=$(echo $authh | sed 's/.*service="\([^"]*\)".*/\1/')
authscope=$(echo $authh | sed 's/.*scope="\([^"]*\)".*/\1/')

res=$(curl -fsSL "https://$username:$password@$authhost?service=$authservice&scope=$authscope")
echo "$res" | jq '{headers:{"Authorization": [("Bearer " + .token)]}}'
```
It works, but it doesn't look very pretty to me (I'm not sure if this will work if the scope changes)

Is there any particular reason why this no longer works?

**Comment by thesayyn** [comment]
This is due to limitation in Bazel where rules_oci can't see what headers the server has sent, therefore can't perform the `WWW-Authenticate` challenge unless the challenge unless it is listed here https://github.com/bazel-contrib/rules_oci/blob/e4ceef02ad9f03551c7473c17482a39776ce4e24/oci/private/authn.bzl#L10

This worked in rules_docker because it did not use Bazels Http Downloader for pulling images, for better or worse. 

May i ask why are you using a credential helper? You should be able to use existing docker auth mechanisms.

**Comment by pierfale** [comment]
When I do a docker login to generate the "auths" entry in .docker/config.json, I get an error 401 when pulling from my registry. I will try to patch rules_oci to add an entry in _WWW_AUTH en see if this work.

Thank you

**Comment by thesayyn** [comment]
Closing this in favor of https://github.com/bazel-contrib/rules_oci/issues/126
