### ISSUE TITLE
oci_tarball doesn't handle base images

### ISSUE THREAD

**Issue by peakschris** [bazel-contrib/rules_oci#584]
I have an issue with oci_tarball. I am using it to publish an oci_image to a local containerd registry, and then consuming from that registry with diffoci. My oci image is several images deep in a hierarchy:

oci.pull("A")
oci_image(name="B", base="A")
oci_image(name="C", base="B")
oci_tarball(name="C_tarball", image="C")

When I bazel run //:C_tarball, any updates to B are not included, nor are changes to B pushed to containerd. This means that diffoci sees the wrong content.

It isn't clear to me whether C_tarball should contain files from A and B, and if not, how bazel should know that a C_tarball push also needs to push B_tarball to containerd

This scenario works fine under oci_push, just not oci_tarball.

Any guidance on if this is user error or if there is a gap here would be very welcome. Thanks!

**Comment by thesayyn** [comment]
> any updates to B are not included

what does this mean? do you mean that files in the oci_image#b is not included in your final image or you don't see an image in your image store?


> It isn't clear to me whether C_tarball should contain files from A and B

oci_tarball does not do anything other than taking an oci-layout image (which contains everything) and translate it to a tarball so that it can be loaded onto the daemon. 


> how bazel should know that a C_tarball push also needs to push B_tarball to containerd

i believe you have a different idea of how `base` attribute in `oci_image` works, so when you depend on another `oci_pull | oci_image` via base attribute what happens is that oci_image copies everything from the previous image into itself. 

hence `extending` chain of oci_image's don't turn into multiple images in your local daemon or remote registry.


> This scenario works fine under oci_push

I don't think oci_tarball is any different than oci_push in this sense, they both take an oci_image and transfer blobs to a destination, if the blob already exists in the destination, it's transfer is skipped.

**Comment by thesayyn** [comment]
I am closing this as it works as expected.
